name: Innoldb Test Coverage

on: 
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    name: Unit Tests
    permissions: 
      repository-projects: write
      pull-requests: write
      checks: write
      id-token: write
    runs-on: ubuntu-18.04
    environment: actions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      # - uses: actions/cache@v2
      #   id: cache
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -r ./src/innoldb/tests/requirements.txt
          curl https://deepsource.io/cli | sh
      - name: Build test application
        run: |
          VERSION=$(cat version.txt)
          python -m build
          cd dist
          pip install innoldb-${VERSION}-py3-none-any.whl
          cd ..
        shell: bash
      - name: Run unit tests and upload coverage
        run: |
          coverage run --source="./src/innoldb/" \
                        --omit="**/test_*.py","**/__init__.py" \
                        --module pytest \
                        --junit-xml=coverage-execution.xml
          coverage xml
          ./bin/deepsource report --analyzer test-coverage --key python --value-file coverage.xml 
        shell: bash
        env:
          DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}
